[package]
authors = ["Reece Stevens <reecestevens24@gmail.com>"]
edition = "2018"
name = "embedded-hal-mock"
version = "0.1.0"

[dependencies]
nb = "0.1.1"

[dependencies.embedded-hal]
version = "0.2.1"
features = ["unproven"]
